"""initial_structure

Revision ID: 221e5bb13e5a
Revises: 
Create Date: 2026-01-26 09:55:48.063153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '221e5bb13e5a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('cookie', sa.Text(), nullable=False),
    sa.Column('login_type', sa.String(length=20), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('fail_count', sa.Integer(), nullable=True),
    sa.Column('last_selected_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_sessions_account_id'), ['account_id'], unique=False)

    op.create_table('download_job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('source_owner_id', sa.String(), nullable=True),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('filename_template', sa.String(), nullable=True),
    sa.Column('target_quality', sa.String(), nullable=True),
    sa.Column('embed_cover', sa.Boolean(), nullable=True),
    sa.Column('embed_lyrics', sa.Boolean(), nullable=True),
    sa.Column('embed_metadata', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_tasks', sa.Integer(), nullable=True),
    sa.Column('completed_tasks', sa.Integer(), nullable=True),
    sa.Column('failed_tasks', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('download_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_download_job_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_download_job_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_download_job_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_download_job_source_owner_id'), ['source_owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_download_job_status'), ['status'], unique=False)

    op.create_table('download_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('music_id', sa.String(), nullable=False),
    sa.Column('music_title', sa.String(), nullable=True),
    sa.Column('music_artist', sa.String(), nullable=True),
    sa.Column('music_album', sa.String(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('quality', sa.String(), nullable=True),
    sa.Column('progress_flags', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_format', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['download_job.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'music_id', name='uq_job_music')
    )
    with op.batch_alter_table('download_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_download_task_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_download_task_music_id'), ['music_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_download_task_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_download_task_status'))
        batch_op.drop_index(batch_op.f('ix_download_task_music_id'))
        batch_op.drop_index(batch_op.f('ix_download_task_job_id'))

    op.drop_table('download_task')
    with op.batch_alter_table('download_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_download_job_status'))
        batch_op.drop_index(batch_op.f('ix_download_job_source_owner_id'))
        batch_op.drop_index(batch_op.f('ix_download_job_source_id'))
        batch_op.drop_index(batch_op.f('ix_download_job_job_type'))
        batch_op.drop_index(batch_op.f('ix_download_job_enabled'))

    op.drop_table('download_job')
    with op.batch_alter_table('account_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_sessions_account_id'))

    op.drop_table('account_sessions')
    # ### end Alembic commands ###
